#!/usr/bin/env bash
# mherbst/autostart
# 2023.10.09 @ 08:37

# source all dependencies
# for herbstluftwm

# env
hc() {
  herbstclient "$@"
}
export HLWM_CONFIG_DIR="$HOME/.config/herbstluftwm"
export -f hc

hc emit_hook reload

source "$HLWM_CONFIG_DIR"/bin/key
source "$HLWM_CONFIG_DIR"/bin/rule
source "$HLWM_CONFIG_DIR"/bin/theme

