#!/usr/bin/env bash
# mherbst/theme/default
# 2023.10.09 @ 09:30

## wallpaper
hsetroot -solid '#5a8e3a'

## appearance
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.title_height 15
hc attr theme.title_when always
hc attr theme.title_font 'monospace:pixelsize=12'
hc attr theme.title_depth 3

hc attr theme.inner_width 1
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1

hc attr theme.tiling.outer_width 1

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

## colorscheme
# base
hc attr theme.tab_color              '#1F1F1Fdd'
hc attr theme.title_color            '#ffffff'
hc attr theme.floating.outer_color    black
hc attr theme.background_color       '#141414'
hc attr theme.inner_color             black

# normal
hc set  frame_bg_normal_color        '#565656aa'
hc set  frame_border_normal_color    '#101010cc'

hc attr theme.normal.title_color     '#898989'
hc attr theme.normal.color           '#323232dd'
hc attr theme.normal.inner_color     '#606060'

# active
hc set  frame_border_active_color    '#222222cc'
hc set  frame_bg_active_color        '#345F0Caa'
hc attr theme.active.color           '#345F0Cef'
hc attr theme.active.tab_color       '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.active.inner_color     '#789161'

# urgent
hc attr theme.urgent.color           '#7811A1dd'
hc attr theme.urgent.inner_color     '#9A65B0'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

